version: "3"
services:
  web:
    # image: wodby/drupal-php:$PHP_TAG
    build: .
    container_name: "mongo_web"
    ports: 
      - "8888:80"
    volumes:
      - ./:/var/www/html
      # - ./php.ini:/usr/local/etc/php/php.ini

  # myproject_mongodb:
  #   container_name: myproject_mongodb
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:  # backup mongo
      - ./tmp/mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example